### ISSUE TITLE
Selectors not updating

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/nexus-allowlist#27]
When mounting `/allowlists` from Azure storage, changes to the files don't seem to trigger the filewatcher which updates the allowlist.

**Comment by JimMadge** [comment]
I would guess this is because the way the storage is presented isn't compatible with the way `entr` works.

It would be worth trying [this](https://github.com/eradman/entr#docker-and-wsl) to see if that is an easy fix.

Could look at other options. I want to avoid writing a daemon in Python though.

**Comment by jemrobinson** [comment]
Can you make a PR on the DSH repo to test out this environment variable?

**Comment by jemrobinson** [comment]
I'm wondering whether something like this would work:

```bash
OLD_HASH=""
while True; do
    NEW_HASH=$(sha256sum <the files we want>)
    if [ "$NEW_HASH" != "$OLD_HASH" ]; then
        update
        OLD_HASH=NEW_HASH
      fi
done
```
