### ISSUE TITLE
CRAN content selector only allows latest package version

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/nexus-allowlist#57]
The current CRAN content selector for Tier 3 is 
https://github.com/alan-turing-institute/nexus-allowlist/blob/442329df3045549c1e45cbd41828b4a4c3e11927/nexus_allowlist/actions.py#L219

This only allows access to the latest version of packages on CRAN, as older versions have a differently constructed URL. For example, `https://cran.r-project.org/src/contrib/MASS_7.3-61.tar.gz` vs `https://cran.r-project.org/src/contrib/Archive/MASS/MASS_7.3-60.tar.gz`

**Comment by JimMadge** [comment]
@craddm could you write an expression (or the regex) to allow the latest and archive packages?

The rules are [here](https://help.sonatype.com/en/content-selectors.html)
